version: "3.8"

services:
  db:
    image: supabase/postgres:14.1.0.106
    container_name: agentset-db
    env_file:
      - .env
    volumes:
      - ./dev/postgres:/docker-entrypoint-initdb.d/
      - ./data/postgres:/var/lib/postgresql/data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf -c max_prepared_transactions=2000
    environment:
      POSTGRES_HOST: /var/run/postgresql
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # PGDATA: /data/postgres
  supavisor:
    image: supabase/supavisor:1.1.39
    container_name: supavisor
    env_file:
      - .env
    ports:
      - 4000:4000
      - 5432:5432
      - 6543:6543 # transaction proxy port if needed
    depends_on:
      - db
    environment:
      PORT: 4000
      PROXY_PORT_SESSION: 5432
      PROXY_PORT_TRANSACTION: 6543
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      CLUSTER_POSTGRES: "true"
      REGION: "local"
      SECRET_KEY_BASE: "12345678901234567890121234567890123456789012345678903212345678901234567890123456789032123456789012345678901234567890323456789032"
      VAULT_ENC_KEY: "12345678901234567890123456789032"
      API_JWT_SECRET: dev
      METRICS_JWT_SECRET: "dev"
      ERL_AFLAGS: -proto_dist inet_tcp
    command: sh -c "/app/bin/migrate && /app/bin/server"
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:4000/api/health"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 12

  # supavisor-init:
  #   image: curlimages/curl:latest
  #   container_name: supavisor-init
  #   env_file:
  #     - .env
  #   depends_on:
  #     supavisor:
  #       condition: service_healthy
  #   command: |
  #     sh -c "
  #     echo 'Creating tenant ${TENANT_ID}...';
  #     curl -s -X PUT \"http://supavisor:4000/api/tenants/${TENANT_ID}\" -H \"Authorization: Bearer ${JWT}\" -H \"Accept: application/json\" -H \"Content-Type: application/json\" -d \"{\
  #       \"tenant\": {\
  #         \"db_host\": \"db\",\
  #         \"db_port\": 5432,\
  #         \"db_database\": \"${POSTGRES_DB}\",\
  #         \"ip_version\": \"auto\",\
  #         \"require_user\": true,\
  #         \"upstream_ssl\": false,\
  #         \"enforce_ssl\": false,\
  #         \"users\": [{\
  #           \"db_user\": \"${POSTGRES_USER}\",\
  #           \"db_password\": \"${POSTGRES_PASSWORD}\",\
  #           \"mode_type\": \"transaction\",\
  #           \"pool_checkout_timeout\": 10000,\
  #           \"pool_size\": 10\
  #         }]\
  #       }\
  #     }\"
  #     echo 'Tenant created.';
  #     "
  # command: |
  #   echo 'Creating tenant ${TENANT_ID}...';
  #   curl -s -X PUT http://supavisor:4000/api/tenants/${TENANT_ID} \
  #     -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNjQ1MTkyODI0LCJleHAiOjE5NjA3Njg4MjR9.M9jrxyvPLkUxWgOYSf5dNdJ8v_eRrq810ShFRT8N-6M" \
  #     -H "Accept: application/json" \
  #     -H "Content-Type: application/json" \
  #      -d "{\
  #       \"tenant\": {\
  #         \"db_host\": \"db\",\
  #         \"db_port\": 5432,\
  #         \"db_database\": \"${POSTGRES_DB}\",\
  #         \"ip_version\": \"auto\",\
  #         \"require_user\": true,\
  #         \"upstream_ssl\": false,\
  #         \"enforce_ssl\": false,\
  #         \"users\": [{\
  #           \"db_user\": \"${POSTGRES_USER}\",\
  #           \"db_password\": \"${POSTGRES_PASSWORD}\",\
  #           \"mode_type\": \"transaction\",\
  #           \"pool_checkout_timeout\": 10000,\
  #           \"pool_size\": 10\
  #         }]\
  #       }\
  #     }";
  #   echo 'Tenant created.';
